core/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TimeDiscountViewSet, LogoutView, BucketViewSet, ProductViewSet, OrderViewSet, CreateCheck, \
    user_detail_api_view, product_list_xml, TelegramShopsViewSet
from rest_framework.authtoken.views import obtain_auth_token

router = DefaultRouter()
router.register('time_discount', TimeDiscountViewSet)
router.register('bucket', BucketViewSet)
router.register('product', ProductViewSet)
router.register('order', OrderViewSet)
router.register('shop_for_telegram', TelegramShopsViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token),
    path('logout/', LogoutView.as_view()),
    path('create-check/', CreateCheck.as_view(), name='create-check'),
    path('user/<int:id>', user_detail_api_view),
    path('<int:partner_id>/kaspi_xml', product_list_xml),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('shop.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', ShopListView.as_view(), name='home'),
    path('shop/<int:shop_id>', ShopMainView.as_view(), name='shop_view'),
    path('create/', ShopCreateView.as_view(), name='shop_create'),
    path('update/<int:id>', ShopUpdateView.as_view(), name='shop_update'),
    path('delete/<int:id>', ShopDeleteView.as_view(), name='shop_delete'),
    path('shop/catalog', shop.ShopCatalogView.as_view(), name='shop_catalog'),

    path('shop/<int:shop_id>/create_product/', ProductCreateView.as_view(), name='create_product'),
    path('shop/<int:shop_id>/products/', ProductListView.as_view(), name='shop_products'),
    path('product/<int:id>', DetailProduct.as_view(), name='detail_product'),
    path('product/<int:id>/edit/', EditProduct.as_view(), name='edit_product'),
    path('product/<int:id>/delete/', DeleteProduct.as_view(), name='delete_product'),
    path('product/<int:id>/attributes/add/', AttributesCreateView.as_view(), name='add_attributes'),
    path('product/<int:id>/attributes/update/', AttributesUpdateView.as_view(), name='update_attributes'),

    path('profile/<int:id>/', Profile.as_view(), name='profile'),
    path('profile/<int:id>/statistic/', Statistic.as_view(), name='statistic'),
    path('profile/shop/<int:id>/products/', ShopProductView.as_view(), name='shop_products'),
    path('profile/shop/<int:id>/orders/', ShopOrderListView.as_view(), name='shop_orders'),
    path('profile/shop/<int:id>/orders/<int:order_id>/', OrderDetailView.as_view(), name='detail_order'),

    path('shop/<int:shop_id>/cart/', BucketListView.as_view(), name='bucket'),
    path('shop/<int:shop_id>/orders/', OrderListView.as_view(), name='orders'),
    path('pay/', Pay.as_view(), name='success_payment')

]

core/shop/models/accountshops.py
from django.db import models


class AccountShops(models.Model):
    account = models.ForeignKey('accounts.Account', on_delete=models.CASCADE, related_name='shop_account')
    shop = models.ForeignKey('shop.Shop', on_delete=models.CASCADE, related_name='account_shops')

core/shop/models/attributes.py
from django.db import models


class Attributes(models.Model):
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='attributes')
    name = models.CharField(max_length=100, blank=False, null=False)
    value = models.CharField(max_length=100)

core/shop/models/bucket.py
from django.db import models

from accounts.models import User, Account
from shop.models import Product, Shop


class Bucket(models.Model):
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
        related_name='shop'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product_in_bucket'
    )
    quantity = models.PositiveIntegerField(
        null=True,
        blank=True,
        default=0,
        verbose_name='Количество'
    )
    unit_price = models.DecimalField(
        decimal_places=2,
        max_digits=13,
        null=True,
        blank=True,
        default=0,
        verbose_name='Цена за единицу'
    )
    user = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='bucket_user'
    )

    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
    )

core/shop/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

core/shop/models/city.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=100)
    city_code = models.IntegerField()

    def __str__(self):
        return f'{self.name}'

core/shop/models/images.py
from django.db import models

from core import settings


class Images(models.Model):
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=settings.PRODUCT_IMG_UPLOAD_PATH)

core/shop/models/orderproducts.py
from django.db import models

from shop.models import Product, Order


class OrderProducts(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price_per_product = models.DecimalField(decimal_places=2, max_digits=10)

core/shop/models/partner_product.py
from django.db import models


class PartnerProduct(models.Model):
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='partner_product')
    partner_shop = models.ForeignKey('shop.PartnerShop', on_delete=models.CASCADE, related_name='partner_product')
    city = models.ForeignKey('shop.City', on_delete=models.CASCADE, related_name='partner_product')

core/shop/models/product.py
from django.db import models
from shop.models import Shop
from taggit.managers import TaggableManager


class Product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Название продукта')
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name='Описание')
    vendor_code = models.IntegerField(unique=True, null=False, blank=False, verbose_name='Код Поставщика')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    price = models.DecimalField(decimal_places=2, max_digits=10, null=False, blank=False, verbose_name='Цена')
    discount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='Скидка')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, related_name='products',
                                 verbose_name='Категория', null=True)
    discounted_price = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, verbose_name='Цена со скдикой')
    tags = TaggableManager(blank=True, verbose_name='Тэги', related_name='products')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-id']

    def __str__(self):
        return f'{self.name}, {self.price}'

core/shop/views/additional_functions.py
import decimal

from shop.models import TimeDiscount


def get_client_ip(request) -> str:
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    return ip


def get_discount(item) -> None:
    product = item.product
    quantity = decimal.Decimal(item.quantity)
    item.unit_price = product.price * quantity

    if discount := product.discounted_price:
        item.unit_price = discount * quantity

    if TimeDiscount.objects.filter(product=product).exists():
        time_discount = TimeDiscount.objects.get(product=product)
        item.unit_price = time_discount.discounted_price * quantity
    item.save()

core/shop/views/attributes.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from shop.models import Attributes, Product


class AttributesCreateView(PermissionRequiredMixin, CreateView):
    model = Attributes
    template_name = 'product/add_attributes.html'
    fields = ['name', 'value']

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)
    def has_permission(self):
        return self.product.shop.user == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = self.product.shop
        return context

    def post(self, request, *args, **kwargs):
        data = dict(zip(request.POST.getlist('name'), request.POST.getlist('value')))

        for name, value in data.items():
            Attributes.objects.create(product=self.product, name=name, value=value)

        return redirect('shop_products', id=self.product.shop_id)


class AttributesUpdateView(PermissionRequiredMixin, UpdateView):
    model = Attributes
    template_name = 'product/edit_attributes.html'
    fields = ['name', 'value']
    pk_url_kwarg = 'id'
    object = None

    def has_permission(self):
        return self.product.shop.user == self.request.user

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['attributes'] = self.get_queryset()
        return context

    def get_queryset(self):
        if Attributes.objects.filter(product=self.product).exists():
            return Attributes.objects.filter(product=self.product)
        return None

    def get(self, request, *args, **kwargs):
        if not self.get_queryset():
            return redirect('add_attributes', id=self.product.id)
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        data = dict(zip(request.POST.getlist('name'), request.POST.getlist('value')))

        for name, value in data.items():
            Attributes.objects.update_or_create(product=self.product, name=name, value=value)

        self.delete_unused_attributes(data)

        return redirect('shop_products', id=self.product.shop_id)

    def delete_unused_attributes(self, data):
        for attribute in self.get_queryset():
            if attribute.name not in data:
                attribute.delete()

core/shop/views/bucket.py
from django.views.generic import ListView

from shop.models import Bucket, Shop, Product


class BucketListView(ListView):
    template_name = 'shop/bucket.html'
    model = Bucket
    context_object_name = 'bucket'
    extra_context = {
        'shops': Shop.objects.all(),
    }

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if user.is_authenticated:
            bucket_items = Bucket.objects.filter(user=user.id)
        else:
            ip_address = self.get_client_ip(self.request)
            bucket_items = Bucket.objects.filter(ip_address=ip_address)

        total_price_by_shop = {}

        for item in bucket_items:
            item.unit_price = item.product.price * item.quantity
            shop_name = item.product.shop.name
            total_price_by_shop[shop_name] = total_price_by_shop.get(shop_name, 0) + item.unit_price

        context['total_price'] = sum(item.unit_price for item in bucket_items)
        context['bucket'] = bucket_items
        context['total_price_by_shop'] = total_price_by_shop

        return context

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')

        return ip

core/shop/views/order.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import When, Case, IntegerField, Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from shop.forms import OrderForm
from shop.models import Bucket, Shop, Order, Product, OrderProducts
from .additional_functions import get_client_ip, get_discount


class BucketListView(CreateView):
    template_name = 'orders/bucket.html'
    model = Order
    form_class = OrderForm

    def dispatch(self, request, *args, **kwargs):
        self.user = self.request.user
        self.shop_id = self.kwargs['shop_id']

        try:
            self.bucket_items = Bucket.objects.filter(user=self.user.account, shop_id=self.shop_id)
        except (Bucket.DoesNotExist, AttributeError):
            ip_address = get_client_ip(self.request)
            self.bucket_items = Bucket.objects.filter(ip_address=ip_address, shop_id=self.shop_id)

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        self.get_form_data(context)
        for item in self.bucket_items:
            get_discount(item)

        context['bucket'] = self.bucket_items
        context['total_price'] = sum(item.unit_price for item in self.bucket_items)
        context['shop'] = Shop.objects.get(id=self.shop_id)
        context['products'] = {item.product: item for item in self.bucket_items}
        context['items'] = ', '.join(str(item.id) for item in self.bucket_items)

        return context

    def get_form_data(self, context):
        try:
            account = self.user.account
            data = {
                'payer_name': self.user.first_name,
                'payer_surname': self.user.last_name,
                'payer_email': self.user.email,
                'payer_phone': self.user.phone,
                'payer_city': account.city,
                'payer_address': account.address,
                'payer_postal_code': account.postal_code,
            }
            context['form'] = OrderForm(initial=data)
        except AttributeError:
            pass

    def get_success_url(self):
        return reverse_lazy('payment', kwargs={'order_id': self.object.id})


class OrderListView(ListView):
    model = Order
    template_name = 'orders/orders.html'
    context_object_name = 'orders'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(id=self.kwargs['shop_id'])
        return context

    def get_queryset(self):
        try:
            return Order.objects.filter(shop__id=self.kwargs['shop_id'], account=self.request.user.account)
        except AttributeError:
            return Order.objects.filter(shop__id=self.kwargs['shop_id'], user_ip=get_client_ip(self.request))


class ShopOrderListView(ListView, PermissionRequiredMixin):
    model = Order
    template_name = 'profile/shop_orders.html'
    context_object_name = 'orders'

    def dispatch(self, request, *args, **kwargs):
        self.shop = Shop.objects.get(id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)

    def has_permission(self):
        return self.request.user == self.shop.user

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = self.shop
        return context

    def get_queryset(self):
        queryset = Order.objects.filter(shop__id=self.shop.id)

        if query := self.request.GET.get('search'):
            queryset = queryset.filter(id__icontains=query)
        return queryset


class OrderDetailView(DetailView):
    model = Order
    pk_url_kwarg = 'order_id'
    template_name = 'profile/detail_shop_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(id=self.kwargs['id'])
        context['orders'] = OrderProducts.objects.filter(order_id=self.kwargs['order_id'])
        return context

core/shop/views/pay.py
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from accounts.models import User, Account
from shop.models import Order, Bucket, OrderProducts


@method_decorator(csrf_exempt, name='dispatch')
class Pay(View):
    def post(self, request, *args, **kwargs):
        account_id = request.POST.get('AccountId')
        token = request.POST.get('Token')
        try:
            account = Account.objects.get(id=account_id)
            account.token = token
            account.save()
        except Account.DoesNotExist:
            pass

        order_id = request.POST.get('InvoiceId')
        order = Order.objects.get(id=order_id)
        order.is_paid = True
        order.save()
        return JsonResponse({'code':0})

core/shop/templates/product/add_attributes.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
    <script src="{% static 'js/add_attributes.js' %}" defer></script>
{% endblock %}
{% block content %}
    <div class="product-upload-container" style="max-width: 1000px">
        <h2 class="form-title">Добавить атрибуты товара</h2>
        <p>Здесь вы можете изменить атрибуты к своему товару. Такие как: цвет, материал, модель и т.д.</p>
        <p>Если атрибут имеет несколько значений, то разделяйте их запятой. Например, цвет: Синий, Чёрный</p>
        <form method="post" class="product-form">
            {% csrf_token %}
            <div class="mb-3" id="attributes-div">
                <div class="d-flex mx-5 mb-3">
                    <div class="d-flex align-items-center">
                        <label for="id_name" class="w-75">Название атрибута</label>
                        <input type="text" class="form-control" id="id_name" name="name"
                               value="{{ form.name.value|default:'' }}" required>
                    </div>
                    <div class="d-flex ms-5 align-items-center">
                        <label for="id_value" class="w-75">Значение атрибута</label>
                        <input type="text" class="form-control" id="id_value" name="value"
                               value="{{ form.value.value|default:'' }}">
                    </div>
                </div>
            </div>
            <small class="mt-2">
                <button type="button" class="btn border-danger p-1 mt-1 ms-3 float-end"
                        style="font-size: 14px" id="del-btn">
                    Убрать последний атрибут
                </button>
                <button type="button" class="btn border-secondary p-1 mt-1 float-end"
                        style="font-size: 14px" id="add-btn">
                    Добавить атрибут
                </button>
            </small>
            <button type="submit" class="btn btn-submit">Добавить к товару</button>
            <a type="button" href="{% url 'shop_products' id=shop.id %}" class="btn btn-light border py-2">Добавить
                позже</a>
        </form>
    </div>
{% endblock %}

core/shop/templates/product/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
    <script src="{% static 'js/new_category.js' %}" defer></script>
{% endblock %}
{% block content %}
    <div class="product-upload-container">
        <h2 class="form-title">Добавить товар</h2>
        <form method="post" enctype="multipart/form-data" class="product-form">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Название</label>
                <input type="text" class="form-control custom-input" id="id_name" name="name"
                       value="{{ form.name.value|default:'' }}" required>
                {% if form.name.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.name.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Описание</label>
                <textarea class="form-control custom-input" id="id_description"
                          name="description">{{ form.description.value|default:'' }}</textarea>
                {% if form.description.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.description.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_name" class="form-label">Категория</label>
                {{ form.category }}
                <small class="mt-2">Нет подходящей категории?
                    <button type="button" class="btn border-secondary p-1 mt-1" style="font-size: 14px"
                            id="category-btn">Добавить
                    </button>
                </small>
                {% if form.category.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.category.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3" hidden id="div-new-category">
                <label for="id_new_category" class="form-label">Новая категория</label>
                <input type="text" class="form-control custom-input" id="id_new_category" name="new_category">
            </div>
            <div class="mb-3">
                <label for="id_vendor_code" class="form-label">Артикул</label>
                <input type="number" class="form-control custom-input" id="id_vendor_code" name="vendor_code"
                       value="{{ form.vendor_code.value|default:'' }}" required>
                {% if form.vendor_code.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.vendor_code.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_quantity" class="form-label">Количество</label>
                <input type="number" class="form-control custom-input" id="id_quantity" name="quantity"
                       value="{{ form.quantity.value|default:'' }}" required>
                {% if form.quantity.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.quantity.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_price" class="form-label">Цена</label>
                <input type="number" class="form-control custom-input" id="id_price" name="price" step="0.01"
                       value="{{ form.price.value|default:'' }}" required>
                {% if form.price.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.price.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_discount" class="form-label">Постоянная скидка</label>
                <input type="number" class="form-control custom-input" id="id_discount" name="discount"
                       value="{{ form.discount.value|default:'' }}">
                {% if form.discount.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.discount.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_images" class="form-label">Изображения товара (максимум 3 изображения)</label>
                {{ image_form.image }}
            </div>
            {% if image_form.image.errors %}
                <div class="alert alert-danger mt-3">
                    {{ image_form.image.errors }}
                </div>
            {% endif %}
            <div class="mb-3">
                <label for="id_tags" class="form-label">Тэги</label>
                <input type="text" class="form-control custom-input" id="id_tags" name="tags"
                       placeholder="Введите теги, разделяя их точкой или точкой с запятой"
                       value="{{ product.tags.all|join:'; '|default:'' }}">
                <small class="form-text text-muted">Введите теги, разделяя их точкой или точкой с запятой, без пробелов. Например:
                    тег1; тег2; тег3 или тег1. тег2. тег3.</small>
                {% if form.tags.errors %}
                    <div class="alert alert-danger mt-3">
                        {{ form.tags.errors }}
                    </div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-submit">Добавить</button>
        </form>
    </div>
{% endblock %}

core/shop/templates/product/edit_attributes.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
    <script src="{% static 'js/add_attributes.js' %}" defer></script>
{% endblock %}
{% block content %}
    <div class="product-upload-container" style="max-width: 1000px">
        <h2 class="form-title">Изменить атрибуты товара</h2>
        <p>Здесь вы можете изменить атрибуты к своему товару. Такие как: цвет, материал, модель и т.д.</p>
        <p>Если атрибут имеет несколько значений, то разделяйте их запятой. Например, цвет: Синий, Чёрный</p>
        <form method="post" class="product-form">
            {% csrf_token %}
            <div class="mb-3" id="attributes-div">

                {% for attribute in attributes %}
                    <div class="d-flex mx-5 mb-3">
                        <div class="d-flex align-items-center">
                            <label for="id_name" class="w-75">Название атрибута</label>
                            <input type="text" class="form-control" id="id_name" name="name"
                                   value="{{ attribute.name }}" required>
                        </div>
                        <div class="d-flex ms-5 align-items-center">
                            <label for="id_value" class="w-75">Значение атрибута</label>
                            <input type="text" class="form-control" id="id_value" name="value"
                                   value="{{ attribute.value }}">
                        </div>
                    </div>
                {% endfor %}
            </div>
            <small class="mt-2">
                <button type="button" class="btn border-danger p-1 mt-1 ms-3 float-end"
                        style="font-size: 14px" id="del-btn">
                    Убрать последний атрибут
                </button>
                <button type="button" class="btn border-secondary p-1 mt-1 float-end"
                        style="font-size: 14px" id="add-btn">
                    Добавить атрибут
                </button>
            </small>
            <button type="submit" class="btn btn-submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

core/shop/templates/product/product_kaspi.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Form Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<style>
    .marg{
        margin-top: 100px;
    }
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top px-3 {% if shop.theme == 'blue' %} bg-primary {% endif %}"
     style="box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); background-color: {{ shop.theme }}">
    <div class="d-flex align-items-center">
        <img class="rounded-circle mr-3" style="object-fit: cover" src="{{ shop.logo.url }}" width="50" height="50"
             alt="{{ shop.name }}">
        <div class="ms-3"
             style="color: {% if shop.theme == 'white' %} black {% else %} white {% endif %}">{{ shop.name }}</div>
    </div>
    <button class="navbar-toggler me-4 {% if shop.theme == 'white' %}{% else %} border-white{% endif %}" type="button"
            data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon color-white"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end me-5" id="navbarNav">
        <ul class="navbar-nav">
            {% if shop.user == request.user %}
                <li class="nav-item">
                    <a class="nav-link text-{% if shop.theme == 'white' %}black{% else %}white{% endif %} ms-3"
                       href="{% url 'profile' shop.user.id %}">Личный кабинет</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link text-{% if shop.theme == 'white' %}black{% else %}white{% endif %} ms-3"
                   href="{% url 'shop_view' shop_id=shop.id %}">Главная страница</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-{% if shop.theme == 'white' %}black{% else %}white{% endif %} ms-3"
                   href="{% url 'shop_products' shop_id=shop.id %}">Все товары</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-{% if shop.theme == 'white' %}black{% else %}white{% endif %} ms-3"
                   href="{% url 'bucket' %}">Корзина</a>
            </li>

        </ul>
    </div>
</nav>

<div class="container marg">
    <form class="my-3" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Отправить форму</button>
    </form>

    {% if success_message %}
        <p class="alert alert-success">{{ success_message }}</p>
    {% endif %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>