core/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TimeDiscountViewSet, LogoutView, BucketViewSet, ProductViewSet, OrderViewSet, CreateCheck, \
    user_detail_api_view, product_list_xml, TelegramShopsViewSet
from rest_framework.authtoken.views import obtain_auth_token

router = DefaultRouter()
router.register('time_discount', TimeDiscountViewSet)
router.register('bucket', BucketViewSet)
router.register('product', ProductViewSet)
router.register('order', OrderViewSet)
router.register('shop_for_telegram', TelegramShopsViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token),
    path('logout/', LogoutView.as_view()),
    path('create-check/', CreateCheck.as_view(), name='create-check'),
    path('user/<int:id>', user_detail_api_view),
    path('<int:partner_id>/kaspi_xml', product_list_xml),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('shop.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', ShopListView.as_view(), name='home'),
    path('shop/<int:shop_id>', ShopMainView.as_view(), name='shop_view'),
    path('create/', ShopCreateView.as_view(), name='shop_create'),
    path('update/<int:id>', ShopUpdateView.as_view(), name='shop_update'),
    path('delete/<int:id>', ShopDeleteView.as_view(), name='shop_delete'),
    path('shop/catalog', shop.ShopCatalogView.as_view(), name='shop_catalog'),

    path('shop/<int:shop_id>/create_product/', ProductCreateView.as_view(), name='create_product'),
    path('shop/<int:shop_id>/products/', ProductListView.as_view(), name='shop_products'),
    path('product/<int:id>', DetailProduct.as_view(), name='detail_product'),
    path('product/<int:id>/edit/', EditProduct.as_view(), name='edit_product'),
    path('product/<int:id>/delete/', DeleteProduct.as_view(), name='delete_product'),
    path('product/<int:id>/attributes/add/', AttributesCreateView.as_view(), name='add_attributes'),
    path('product/<int:id>/attributes/update/', AttributesUpdateView.as_view(), name='update_attributes'),

    path('profile/<int:id>/', Profile.as_view(), name='profile'),
    path('profile/<int:id>/statistic/', Statistic.as_view(), name='statistic'),
    path('profile/shop/<int:id>/products/', ShopProductView.as_view(), name='shop_products'),
    path('profile/shop/<int:id>/orders/', ShopOrderListView.as_view(), name='shop_orders'),
    path('profile/shop/<int:id>/orders/<int:order_id>/', OrderDetailView.as_view(), name='detail_order'),

    path('shop/<int:shop_id>/cart/', BucketListView.as_view(), name='bucket'),
    path('shop/<int:shop_id>/orders/', OrderListView.as_view(), name='orders'),
    path('pay/', Pay.as_view(), name='success_payment')

]

core/shop/models/accountshops.py
from django.db import models


class AccountShops(models.Model):
    account = models.ForeignKey('accounts.Account', on_delete=models.CASCADE, related_name='shop_account')
    shop = models.ForeignKey('shop.Shop', on_delete=models.CASCADE, related_name='account_shops')

core/shop/models/attributes.py
from django.db import models


class Attributes(models.Model):
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE, related_name='attributes')
    name = models.CharField(max_length=100, blank=False, null=False)
    value = models.CharField(max_length=100)

core/shop/models/bucket.py
from django.db import models

from accounts.models import User, Account
from shop.models import Product, Shop


class Bucket(models.Model):
    shop = models.ForeignKey(
        Shop,
        on_delete=models.CASCADE,
        related_name='shop'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product_in_bucket'
    )
    quantity = models.PositiveIntegerField(
        null=True,
        blank=True,
        default=0,
        verbose_name='Количество'
    )
    unit_price = models.DecimalField(
        decimal_places=2,
        max_digits=13,
        null=True,
        blank=True,
        default=0,
        verbose_name='Цена за единицу'
    )
    user = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='bucket_user'
    )

    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
    )

core/shop/models/product.py
from django.db import models
from shop.models import Shop
from taggit.managers import TaggableManager


class Product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Название продукта')
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name='Описание')
    vendor_code = models.IntegerField(unique=True, null=False, blank=False, verbose_name='Код Поставщика')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    price = models.DecimalField(decimal_places=2, max_digits=10, null=False, blank=False, verbose_name='Цена')
    discount = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name='Скидка')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, related_name='products',
                                 verbose_name='Категория', null=True)
    discounted_price = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, verbose_name='Цена со скдикой')
    tags = TaggableManager(blank=True, verbose_name='Тэги', related_name='products')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-id']

    def __str__(self):
        return f'{self.name}, {self.price}'

core/shop/models/shop.py
from django.db import models
from django.db.models import TextChoices

from core import settings
from taggit.managers import TaggableManager


class Themes(TextChoices):
    DARK = 'black', 'Темная'
    LIGHT = 'white', 'Светлая'
    BLUE = 'blue', 'Синяя'


class Shop(models.Model):
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
        related_name='shop',
        verbose_name='Владелец магазина',
    )
    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name='Название магазина',
        unique=True
    )
    logo = models.ImageField(
        null=True,
        blank=True,
        upload_to=settings.LOGO_IMG_UPLOAD_PATH,
        verbose_name='Логотип магазина',
        default='def.png'
    )

    description = models.TextField(
        null=True,
        blank=True,
        max_length=2500,
        verbose_name='Описание магазина'
    )

    theme = models.CharField(
        max_length=255,
        choices=Themes.choices,
        default=Themes.DARK,
        verbose_name='Тема магазина'
    )

    partner_id = models.CharField(
        max_length=255,
        verbose_name='ID Партнера(Kaspi)',
        blank=True,
        null=True,
        unique=True
    )

    tg_token = models.CharField(
        max_length=255,
        verbose_name='Телеграм-токен',
        blank=True,
        null=True,
        unique=True
    )

    tags = TaggableManager(blank=True, verbose_name='Тэги')

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'

core/shop/views/additional_functions.py
import decimal

from shop.models import TimeDiscount


def get_client_ip(request) -> str:
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    return ip


def get_discount(item) -> None:
    product = item.product
    quantity = decimal.Decimal(item.quantity)
    item.unit_price = product.price * quantity

    if discount := product.discounted_price:
        item.unit_price = discount * quantity

    if TimeDiscount.objects.filter(product=product).exists():
        time_discount = TimeDiscount.objects.get(product=product)
        item.unit_price = time_discount.discounted_price * quantity
    item.save()

core/shop/views/attributes.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from shop.models import Attributes, Product


class AttributesCreateView(PermissionRequiredMixin, CreateView):
    model = Attributes
    template_name = 'product/add_attributes.html'
    fields = ['name', 'value']

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)
    def has_permission(self):
        return self.product.shop.user == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = self.product.shop
        return context

    def post(self, request, *args, **kwargs):
        data = dict(zip(request.POST.getlist('name'), request.POST.getlist('value')))

        for name, value in data.items():
            Attributes.objects.create(product=self.product, name=name, value=value)

        return redirect('shop_products', id=self.product.shop_id)


class AttributesUpdateView(PermissionRequiredMixin, UpdateView):
    model = Attributes
    template_name = 'product/edit_attributes.html'
    fields = ['name', 'value']
    pk_url_kwarg = 'id'
    object = None

    def has_permission(self):
        return self.product.shop.user == self.request.user

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['attributes'] = self.get_queryset()
        return context

    def get_queryset(self):
        if Attributes.objects.filter(product=self.product).exists():
            return Attributes.objects.filter(product=self.product)
        return None

    def get(self, request, *args, **kwargs):
        if not self.get_queryset():
            return redirect('add_attributes', id=self.product.id)
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        data = dict(zip(request.POST.getlist('name'), request.POST.getlist('value')))

        for name, value in data.items():
            Attributes.objects.update_or_create(product=self.product, name=name, value=value)

        self.delete_unused_attributes(data)

        return redirect('shop_products', id=self.product.shop_id)

    def delete_unused_attributes(self, data):
        for attribute in self.get_queryset():
            if attribute.name not in data:
                attribute.delete()

core/shop/views/bucket.py
from django.views.generic import ListView

from shop.models import Bucket, Shop, Product


class BucketListView(ListView):
    template_name = 'shop/bucket.html'
    model = Bucket
    context_object_name = 'bucket'
    extra_context = {
        'shops': Shop.objects.all(),
    }

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if user.is_authenticated:
            bucket_items = Bucket.objects.filter(user=user.id)
        else:
            ip_address = self.get_client_ip(self.request)
            bucket_items = Bucket.objects.filter(ip_address=ip_address)

        total_price_by_shop = {}

        for item in bucket_items:
            item.unit_price = item.product.price * item.quantity
            shop_name = item.product.shop.name
            total_price_by_shop[shop_name] = total_price_by_shop.get(shop_name, 0) + item.unit_price

        context['total_price'] = sum(item.unit_price for item in bucket_items)
        context['bucket'] = bucket_items
        context['total_price_by_shop'] = total_price_by_shop

        return context

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')

        return ip

core/shop/views/order.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import When, Case, IntegerField, Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from shop.forms import OrderForm
from shop.models import Bucket, Shop, Order, Product, OrderProducts
from .additional_functions import get_client_ip, get_discount


class BucketListView(CreateView):
    template_name = 'orders/bucket.html'
    model = Order
    form_class = OrderForm

    def dispatch(self, request, *args, **kwargs):
        self.user = self.request.user
        self.shop_id = self.kwargs['shop_id']

        try:
            self.bucket_items = Bucket.objects.filter(user=self.user.account, shop_id=self.shop_id)
        except (Bucket.DoesNotExist, AttributeError):
            ip_address = get_client_ip(self.request)
            self.bucket_items = Bucket.objects.filter(ip_address=ip_address, shop_id=self.shop_id)

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        self.get_form_data(context)
        for item in self.bucket_items:
            get_discount(item)

        context['bucket'] = self.bucket_items
        context['total_price'] = sum(item.unit_price for item in self.bucket_items)
        context['shop'] = Shop.objects.get(id=self.shop_id)
        context['products'] = {item.product: item for item in self.bucket_items}
        context['items'] = ', '.join(str(item.id) for item in self.bucket_items)

        return context

    def get_form_data(self, context):
        try:
            account = self.user.account
            data = {
                'payer_name': self.user.first_name,
                'payer_surname': self.user.last_name,
                'payer_email': self.user.email,
                'payer_phone': self.user.phone,
                'payer_city': account.city,
                'payer_address': account.address,
                'payer_postal_code': account.postal_code,
            }
            context['form'] = OrderForm(initial=data)
        except AttributeError:
            pass

    def get_success_url(self):
        return reverse_lazy('payment', kwargs={'order_id': self.object.id})


class OrderListView(ListView):
    model = Order
    template_name = 'orders/orders.html'
    context_object_name = 'orders'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(id=self.kwargs['shop_id'])
        return context

    def get_queryset(self):
        try:
            return Order.objects.filter(shop__id=self.kwargs['shop_id'], account=self.request.user.account)
        except AttributeError:
            return Order.objects.filter(shop__id=self.kwargs['shop_id'], user_ip=get_client_ip(self.request))


class ShopOrderListView(ListView, PermissionRequiredMixin):
    model = Order
    template_name = 'profile/shop_orders.html'
    context_object_name = 'orders'

    def dispatch(self, request, *args, **kwargs):
        self.shop = Shop.objects.get(id=self.kwargs['id'])
        return super().dispatch(request, *args, **kwargs)

    def has_permission(self):
        return self.request.user == self.shop.user

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = self.shop
        return context

    def get_queryset(self):
        queryset = Order.objects.filter(shop__id=self.shop.id)

        if query := self.request.GET.get('search'):
            queryset = queryset.filter(id__icontains=query)
        return queryset


class OrderDetailView(DetailView):
    model = Order
    pk_url_kwarg = 'order_id'
    template_name = 'profile/detail_shop_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(id=self.kwargs['id'])
        context['orders'] = OrderProducts.objects.filter(order_id=self.kwargs['order_id'])
        return context

core/shop/views/pay.py
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from accounts.models import User, Account
from shop.models import Order, Bucket, OrderProducts


@method_decorator(csrf_exempt, name='dispatch')
class Pay(View):
    def post(self, request, *args, **kwargs):
        account_id = request.POST.get('AccountId')
        token = request.POST.get('Token')
        try:
            account = Account.objects.get(id=account_id)
            account.token = token
            account.save()
        except Account.DoesNotExist:
            pass

        order_id = request.POST.get('InvoiceId')
        order = Order.objects.get(id=order_id)
        order.is_paid = True
        order.save()
        return JsonResponse({'code':0})

core/shop/templates/shop/bucket.html
{% extends 'main.html' %}

{% block content%}
<section class="section-content padding-y bg">
    <div class="container">
     {% for shop, total in total_price_by_shop.items %}
     <h6 class="mt-3 text-center">Магазин: {{ shop }}</h6>
    {% for item in bucket %}
    {% if item.product.shop.name == shop %}
        <form class="card" action="" method="post">
            <div class="row no-gutters">
                <aside class="col-md-8 col-lg-9 cart-items-wrapper">
                    <article class="card-body">
                        <div class="row align-items-center">
                            <div class="col-md-7">
                                <figure class="media">
                                    {% for img in item.product.images.all %}
                                    <a href="#" class="img-wrap me-3"> <img class=" border img-sm" src="{{ img.image.url }}" alt=""> </a>
                                    {% endfor %}
                                    <figcaption>
                                        <a href="" class="title h6">{{ item.product.name }}</a>
                                        <p class="text-muted small"></p>
                                        <div class="price-wrap">
                                            <span id="price{{ item.product.price }}">{{ item.product.price }}</span> тг / шт.
                                        </div>
                                    </figcaption>
                                </figure>
                            </div>
                        <div class="col-md-5 text-md-right text-right d-flex" >
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                    <button class="btn btn-light" type="button" id="button-minus" onclick="decrementQuantity('{{ item.id }}')">
                                        -
                                    </button>
                                </div>
                                <input type="text" id="quantity-{{ item.id }}" class="text-center form-control mx-2" name="cart-quantity" value="{{ item.quantity }}">
                                  <div class="input-group-append">
                                      <button class="btn btn-light" type="button" id="button-plus" onclick="incrementQuantity('{{ item.id }}')">
                                          +
                                      </button>

                                  </div>
                            </div>
                                <a href="#" class="delete-from-bucket ms-2 btn btn-light" data-item-id="{{ item.id }}"> <i class="fa fa-trash"></i></a>
                        </div>
                        </div>
                    </article>
                </aside>
            </div>
        </form>
     {% endif %}
    {% endfor %}
           <aside class="border-left cart-aside ">
                <div class="card-body">
                    <dl class="d-flex mb-0 " style="justify-content: space-between">
                        <dl>
                            <strong>Итого:</strong>
                        </dl>
                        <div class="text-right text-dark">
                            <span name="{{shop}}">{{ total }} тг.</span>
                        </div>
                    </dl>
                    <hr>
                    <a href="" class="btn btn-primary btn-block hide-">Оформить заказ</a>
                </div>
            </aside>
    {% endfor %}
    </div>
</section>

{% endblock %}

core/shop/templates/shop/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Catalog</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class='nav-item'>
                                <a class="nav-link-color" href="{% url 'home' %}">Главная страница</a>
                            </li>
                            <li class='nav-item'>
                                <a class="nav-link-color" href="{% if user.is_authenticated %}{% url 'shop_create' %}{% else %}{% url 'login_page' %}{% endif %}">Создать магазин</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
<div class="container">
    <h2 class="mb-3 mt-4">Каталог магазинов</h2>
        {% include 'partial/search_form.html' %}
    <div class="row">
                {% for shop in shops %}
                    <div class="col-12 col-md-4 mb-3 special-col">
                        <a href="{% url 'shop_view' shop_id=shop.id %}" class="card-banner">
                  <span class="card-body widget-collection">
                      <picture>
                          <source type="image/webp" class="inside-collection-image lazy entered"
                                  data-srcset="{{ shop.logo.url }}"
                                  data-ll-status="entered" srcset="{{ shop.logo.url }}">
                          <img class="inside-collection-image lazy entered loaded" src="{{ shop.logo.url }}"
                               data-src="{{ shop.logo.url }}" alt="Аксессуары" data-ll-status="loaded">
                      </picture>
                  </span>
                            <span class="text-bottom">
                      <h5 class="title">{{ shop.name }}</h5>
                  </span>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="mt-5">
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
            </div>
        </div>
</body>
</html>

core/shop/templates/shop/shop_create_update.html
{% extends 'base.html' %} {% block content %}
<div class="product-upload-container">
    <form class="product-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h1 class="main_heading" style='text-align: center'>Создание магазина</h1>
        <hr style="color: red">
        <h4 class="h4" style="text-align: center">Пожалуйста заполните поля</h4>
        <label for="id_name" class="form-label">Название магазина:</label>
        <input id="id_name" class="form-control custom-input" type="text" name="name" placeholder="Название магазина" maxlength="255" required />
        <label for="id_logo">Логотип магазина:</label>
        <input class="custom-input form-control" type="file" name="logo" id="id_logo" />

        <label for="id_description">Описание магазина:</label>
        <textarea class="form-control custom-input" name="description" id="id_description" maxlength="2500" cols="30" rows="3" placeholder="Описание магазина"></textarea>

        <label for="id_theme">Тема магазина:</label>
        <select class="form-control custom-input" id="id_theme" name="theme">
                <option value="black" selected> Темная </option>
                <option value="white"> Светлая </option>
                <option value="blue"> Синяя </option>
            </select>

        <label for="partner_id">ID Партнера(необязательно):</label>
        <input id="partner_id" type="text" class="form-control custom-input" name="partner_id">
        <p style="color: gray;">(Для получения ID Партнера у вас должен быть создан kaspi-магазин)</p>

        <label for="tg_token">Telegram Token(необязательно):</label>
        <input id='tg_token' class="form-control custom-input" type="text" name="tg_token">
        <p style="color: gray;">(Для получения токена вам нужно обратиться в BotFather в telegram)</p>

        <input type="hidden" name="user" value="{{ request.user.id }}">
        <button type="submit" class="btn btn-submit">Создать</button> {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Ошибка!</strong> Пожалуйста, проверьте введенные данные. {{ form.errors }}
        </div>
        {% endif %}
    </form>
</div>

{% endblock %}

core/shop/templates/shop/shop_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10 col-12">
                <div class="card shop-form-card">
                    <div class="card-header text-center">
                        <h2>Редактирование магазина</h2>
                    </div>

                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                                {% if form.name.errors %}
                                    <div class="invalid-feedback">
                                        {{ form.name.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.logo.id_for_label }}">Логотип</label>
                                {{ form.logo }}
                                {% if form.logo.errors %}
                                    <div class="invalid-feedback">
                                        {{ form.logo.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                                {% if form.description.errors %}
                                    <div class="invalid-feedback">
                                        {{ form.description.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.theme.id_for_label }}">Тема</label>
                                {{ form.theme }}
                                {% if form.theme.errors %}
                                    <div class="invalid-feedback">
                                        {{ form.theme.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.partner_id.id_for_label }}">ID Партнера:</label>
                                {{ form.partner_id }}
                                {% if form.partner_id.errors %}
                                    <div class="invalid-feedback">
                                        {{ form.partner_id.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.tg_token.id_for_label }}">Telegram Token:</label>
                                {{ form.tg_token }}
                                {% if form.tg_token.errors %}
                                    <div class="text-danger">
                                        {{ form.tg_token.errors }}
                                    </div>
                                {% endif %}
                            </div>

                            <button type="submit" class="btn btn-primary btn-block">Сохранить изменения</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}